### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by du0ngle** [Issafalcon/neotest-dotnet#111]
Hi!

I am new to using Neovim, and I am trying to make this test plugin work. The plugin is able to detect all the tests with treesitter. However, when running any test, the log shows that no tests can be found, i.e.,

...rt\neotest-dotnet/lua/neotest-dotnet/utils/trx-utils.lua:18 | No test output file found 

I am able to run the test in the following way by using the CLI:

~\TestFolder\bin\x64\Release> dotnet test AllTests.dll --filter "FullyQualifiedName~test1"

How should I configure my settings such that I am able to make this work?

Thanks in advance!

**Comment by Issafalcon** [comment]
Hi @du0ngle . I'm just getting round to addressing issues raised against my plugins. Life changes have meant I've had to move these side projects of mine to lower priority, but just posting to check that this issue has been sorted for you (assuming given the closed status of the issue).
