### ISSUE TITLE
[Feature Request] Dont put fully qualified name to testnames in the OutputPanel

### ISSUE THREAD

**Issue by SimonSchwendele** [Issafalcon/neotest-dotnet#116]
Hi there

I always run my test through the testOutput panel.
Is it possible to display the discovered tests with just their testnames rather than the full name ?

I'd prefer to have the marked test display only as `ExecutionWaitsUntilProcessCompletes`
![image](https://github.com/user-attachments/assets/f518e9c7-f4f5-44d9-8d4b-9c2f48bf3d2d)

**Comment by Issafalcon** [comment]
Hi @SimonSchwendele. I'm just getting round to addressing issues raised against my plugins. Life changes have meant I've had to move these side projects of mine to lower priority, but just posting to say it's still on my radar to fix, and I'll get back to it as soon as I can. This feature would be tricky though, as there is tight coupling between the name of the test, and its link to the position in each file. Most of the control over the test name is done via neotest base. But I'm looking at overhauling this plugin signfiicantly, so it might make this possible.
