### ISSUE TITLE
Incorrect test case filter when the test class is a subclass

### ISSUE THREAD

**Issue by X9VoiD** [Issafalcon/neotest-dotnet#26]
## Reproduction

```
dotnet new xunit -n SubClass
```

UnitTest1.cs
```cs
namespace SubClass;

public class UnitTest1
{
    public class DeeperClass
    {
        [Fact]
        public void Test1()
        {

        }
    }
}
```

Run `Test1()`

## Expected behavior

Should run just fine.

## Actual behavior

```
No test matches the given testcase filter `FullyQualifiedName~UnitTest1.DeeperClass.Test1`
```

The class and the subclass is there but not the root namespace itself. (I also tested doing a deeper namespace instead of class, `SubClass.SubNamespace.UnitTest2` and it works)

**Comment by Issafalcon** [comment]
I'll close this issue as I believe the nesting class issue was fixed as part of #52 .
