### ISSUE TITLE
Incorrect testcase filter when test class is both in deeper namespace and class

### ISSUE THREAD

**Issue by X9VoiD** [Issafalcon/neotest-dotnet#27]
## Reproduction

```
dotnet new xunit -n Deeper.Namespace
```

UnitTest1.cs
```cs
namespace Deeper.Namespace;

public class Deeper
{
    public class TestClass
    {
        [Fact]
        public void Test1()
        {

        }
    }
}
```

Run `Test1()`

## Expected behavior

Should run just fine.

## Actual behavior

```
No test matches the given testcase filter `FullyQualifiedName~Deeper.Namespace.Deeper.TestClass.Test1`
```

`dotnet test -t` shows that the following is the correct filter

```
Deeper.Namespace.Deeper+TestClass.Test1
```

**Comment by Issafalcon** [comment]
Hi @X9VoiD  - Sorry for the delay in getting back to you. I was working on some other issues with the adapter, and I believe, in doing so, have fixed this issue:
![image](https://user-images.githubusercontent.com/19861614/210879376-6d443ab0-0d10-4a76-a386-262ab78c9454.png)

Please give it another go.

**Comment by foldedwave** [comment]
Tested using the following versions -
Neovim - 0.8.1
neotest - fee5ce9bdc3dff4706a29b012e75025ab376becb
neotest-dotnet - a90836af097ffc580f61c55e60c1795f73b728f6
dotnet - 6.0.405
linux - ubuntu 20.04 (x64)

When I run a test from a nested class I still see the test fail because no test matches the supplied filter.
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/4611157/212560077-b8777240-c3ca-4ef5-bd53-b9e5dad23d34.png">

If you would like to replicate you can use this repo - https://github.com/foldedwave/nvim-testing
Ensure you use nvim.sh rather than nvim-dev.sh (nvim-dev.sh has fixes that should make nested test classes work) and run :PackerSync before running the tests.

I believe the issue is relating to fully qualified test names having a '+' in front of nested classes, this matches what what X9VoiD has reported.

**Comment by foldedwave** [comment]
Some extra info on this.

With the current main I see this in the logs - 

```
DEBUG | 2023-01-16T23:28:50Z+0000 | ...te/pack/packer/start/neotest/lua/neotest/client/init.lua:305 | Found { {
    id = "/root/dev/xunit/testproj1/UnitTest1.cs",
    name = "UnitTest1.cs",
    path = "/root/dev/xunit/testproj1/UnitTest1.cs",
    range = { 0, 0, 27, 0 },
    type = "file"
  }, { {
      id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1",
      name = "xunit.testproj1",
      path = "/root/dev/xunit/testproj1/UnitTest1.cs",
      range = { 0, 0, 26, 1 },
      type = "namespace"
    }, { {
        id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1",
        name = "UnitTest1",
        path = "/root/dev/xunit/testproj1/UnitTest1.cs",
        range = { 2, 0, 26, 1 },
        type = "namespace"
      }, { {
          id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::Test1",
          name = "Test1",
          path = "/root/dev/xunit/testproj1/UnitTest1.cs",
          range = { 4, 4, 8, 5 },
          type = "test"
        } }, { {
          id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::Test2",
          name = "Test2",
          path = "/root/dev/xunit/testproj1/UnitTest1.cs",
          range = { 10, 4, 16, 5 },
          type = "test"
        }, { {
            id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::Test2(a: 1)",
            name = "Test2(a: 1)",
            path = "/root/dev/xunit/testproj1/UnitTest1.cs",
            range = { 11, 15, 11, 18 },
            type = "test"
          } }, { {
            id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::Test2(a: 2)",
            name = "Test2(a: 2)",
            path = "/root/dev/xunit/testproj1/UnitTest1.cs",
            range = { 12, 15, 12, 18 },
            type = "test"
          } } }, { {
          id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::NestedClass",
          name = "NestedClass",
          path = "/root/dev/xunit/testproj1/UnitTest1.cs",
          range = { 18, 4, 25, 5 },
          type = "namespace"
        }, { {
            id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::NestedClass::Test1",
            name = "Test1",
            path = "/root/dev/xunit/testproj1/UnitTest1.cs",
            range = { 20, 8, 24, 9 },
            type = "test"
          } } } } } }
```

Incorrectly constructing the filter

```
DEBUG | 2023-01-16T23:57:00Z+0000 | ...ker/start/neotest/lua/neotest/client/strategies/init.lua:33 | Strategy spec {
  command = 'dotnet test /root/dev/xunit/testproj1 --filter FullyQualifiedName~"xunit.testproj1.UnitTest1.NestedClass.Test1" --results-directory /tmp/nvim.root/qHb1Rg --logger "trx;logfilename=0.trx"',
  context = {
    file = "/root/dev/xunit/testproj1/UnitTest1.cs",
    id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::NestedClass::Test1",
    results_path = "/tmp/nvim.root/qHb1Rg/0.trx"
  },
  strategy = {
    height = 40,
    width = 120
  }
}
```

Leading to the tests in the nested class failing -

<img width="409" alt="image" src="https://user-images.githubusercontent.com/4611157/212782176-8ee745cc-0084-4afa-b394-8c0430300e6e.png">

But if you try this branch ( https://github.com/foldedwave/neotest-dotnet/tree/issue27 ) you will see that the inner class is identified correctly

```
DEBUG | 2023-01-16T23:36:33Z+0000 | ...te/pack/packer/start/neotest/lua/neotest/client/init.lua:305 | Found { {
    id = "/root/dev/xunit/testproj1/UnitTest1.cs",
    name = "UnitTest1.cs",
    path = "/root/dev/xunit/testproj1/UnitTest1.cs",
    range = { 0, 0, 27, 0 },
    type = "file"
  }, { {
      id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1",
      is_class = false,
      name = "xunit.testproj1",
      path = "/root/dev/xunit/testproj1/UnitTest1.cs",
      range = { 0, 0, 26, 1 },
      type = "namespace"
    }, { {
        id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1",
        is_class = true,
        name = "UnitTest1",
        path = "/root/dev/xunit/testproj1/UnitTest1.cs",
        range = { 2, 0, 26, 1 },
        type = "namespace"
      }, { {
          id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::Test1",
          is_class = false,
          name = "Test1",
          path = "/root/dev/xunit/testproj1/UnitTest1.cs",
          range = { 4, 4, 8, 5 },
          type = "test"
        } }, { {
          id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::Test2",
          is_class = false,
          name = "Test2",
          path = "/root/dev/xunit/testproj1/UnitTest1.cs",
          range = { 10, 4, 16, 5 },
          type = "test"
        }, { {
            id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::Test2(a: 1)",
            is_class = false,
            name = "Test2(a: 1)",
            path = "/root/dev/xunit/testproj1/UnitTest1.cs",
            range = { 11, 15, 11, 18 },
            type = "test"
          } }, { {
            id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1::Test2(a: 2)",
            is_class = false,
            name = "Test2(a: 2)",
            path = "/root/dev/xunit/testproj1/UnitTest1.cs",
            range = { 12, 15, 12, 18 },
            type = "test"
          } } }, { {
          id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1+NestedClass",
          is_class = true,
          name = "NestedClass",
          path = "/root/dev/xunit/testproj1/UnitTest1.cs",
          range = { 18, 4, 25, 5 },
          type = "namespace"
        }, { {
            id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1+NestedClass::Test1",
            is_class = false,
            name = "Test1",
            path = "/root/dev/xunit/testproj1/UnitTest1.cs",
            range = { 20, 8, 24, 9 },
            type = "test"
          } } } } } }
```

Which allows the test to be correctly filtered

```
DEBUG | 2023-01-16T23:42:55Z+0000 | ...ker/start/neotest/lua/neotest/client/strategies/init.lua:33 | Strategy spec {
  command = 'dotnet test /root/dev/xunit/testproj1 --filter FullyQualifiedName~"xunit.testproj1.UnitTest1+NestedClass.Test1" --results-directory /tmp/nvim.root/THmrdh --logger "trx;logfilename=2.trx"',
  context = {
    file = "/root/dev/xunit/testproj1/UnitTest1.cs",
    id = "/root/dev/xunit/testproj1/UnitTest1.cs::xunit.testproj1::UnitTest1+NestedClass::Test1",
    results_path = "/tmp/nvim.root/THmrdh/2.trx"
  },
  strategy = {
    height = 40,
    width = 120
  }
}
```

and the test results to be collected

<img width="409" alt="image" src="https://user-images.githubusercontent.com/4611157/212781759-10173721-f1d8-4fa2-8115-a719832f1f36.png">


To easily replicate you can use this branch and spin up the docker container - https://github.com/foldedwave/nvim-testing/tree/issue27

**Comment by Issafalcon** [comment]
Thanks for the additional input @foldedwave ! I've been stretched for time recently, so I'll take a more thorough look at your containers again when I get chance. Maybe this weekend I'm hoping.

**Comment by foldedwave** [comment]
No problem, the branch was have linked above only requires changes to this repo rather than also changing neotest itself. It's probably not the ideal approach but I'm happy to help out and make changes as you see fit - this is a very useful plugin for me.

**Comment by Issafalcon** [comment]
So I've taken a closer look at this and I remain stumped. You're correct in that when I run the tests in the docker containers provided, they are failing to correctly identify the nested test class cases. Then, switching to use the `nvim-dev.sh` script to run, the branch from your fork seems to fix this issue.

The bit the I don't understand, is that when I switch to using your same fork (and branch) of neotest-dotnet on my local machine, it fails to link back any of the test nodes with the intermediate results in the `convert_intermediate_results` function of the result_utils. 

I updated my versions of various potential causes of this discrepancy, so I am running:
Neovim - 0.8.1
neotest - fee5ce9bdc3dff4706a29b012e75025ab376becb
neotest-dotnet - https://github.com/Issafalcon/neotest-dotnet/commit/a90836af097ffc580f61c55e60c1795f73b728f6
dotnet - 6.0.405
linux - ubuntu 22.04 (x64) - **this is the only difference on my local machine**

I've run out of time today to go any further, but I think it requires a bit more debugging.

However, there definitely does remain the issue of the nested test class with the '+' in the name, which needs sorting out. 

I feel the best course of action would be to get some unit tests added in to cover all the edge cases, as the code is becoming rather more complex that I started with 😄 

From there, it should be a lot easier to see where the discrepancies lie in various environments.

**Comment by Issafalcon** [comment]
Hi @foldedwave and @X9VoiD ,

Apologies it's taken so long for me to get back on this. It's taken a while for it to resurface to the top of my priorities list. As is life!

Anyway, thanks to the code you had on one of your forks @foldedwave , and getting some additional unit test coverage, I think this issue is now truly resolved (for xunit and nunit frameworks at least).
