### ISSUE TITLE
False negative results with [MemberData] and [AutoData]

### ISSUE THREAD

**Issue by lawrence-laz** [Issafalcon/neotest-dotnet#40]
Running tests with `[MemberData]` or `[AutoData]` individually gives false negative results. While running all tests in the file gives correct results.

Tested with Xunit and dotnet6.

Repro steps:
1. Create Xunit project
```bash
dotnet new xunit -n neotest-false-negative-repro
cd neotest-false-negative-repro
dotnet add package AutoFixture.Xunit2
```
2. Copy/paste these tests:
```csharp
using System.Collections.Generic;
using AutoFixture.Xunit2;
using Xunit;

namespace xunit_tests;

public class UnitTest1
{
    public static IEnumerable<object[]> _bar = new[]
    {
        new object[] {"bar"}
    };

    [Fact]
    public void TestFact() { }

    [Theory, InlineData("foo")]
    public void TestTheoryInlineData(string foo) { }

    [Theory, MemberData(nameof(_bar))]
    public void TestTheoryMemberData(string bar) { }

    [Theory, AutoData]
    public void TestTheoryAutoData(string bar) { }
}
```

3. a) ❌ Put cursor on `TestTheoryMemberData` or `TestTheoryAutoData` and run `:lua require("neotest").run.run()` results in test running and passing, but neo-test reports failure:
![image](https://user-images.githubusercontent.com/8823448/210858642-fcf15368-cb32-4897-be6d-bce1523e87ee.png)
3. b) ✅ Run `require("neotest").run.run(vim.fn.expand("%"))` and all tests pass and neo-test reports success:
![image](https://user-images.githubusercontent.com/8823448/210859143-294c819b-951c-473a-8151-33c164f33604.png)

**Comment by lawrence-laz** [comment]
I dug into this a bit and found that the problem lies in `intermediate_result.test_name` having the test name include the dynamically generated values, for example:
```
Transactional.IO.Tests.TransactionalFileStreamTests.TransactionalFileStream_does_not_modify_file_if_Commit_is_not_called(fileName: "fileName8cc29026-3ea9-42e7-a745-b77e82bbca46", unmodifiedContent: "unmodifiedContent98d5539b-159b-4faf-94b5-fb641ce2d"..., modifiedContent: "modifiedContentbf207186-2d11-4265-905c-bc4849f5b3f"...)
```
These values are not present in a statically generated node tree:
```
TransactionalFileStream_does_not_modify_file_if_Commit_is_not_called
```
And this caused the mapping to fail.

This PR #44 fixes this by trimming dynamically generated values.

All scenarios in the original report now succeed when running individually, as well as file as a whole:
![image](https://user-images.githubusercontent.com/8823448/213831571-692c0796-2e30-4e74-84d4-f12605098230.png)

**Comment by Issafalcon** [comment]
Great! Thanks for the PR @lawrence-laz - I'll take a look at this soon!

**Comment by Tantol** [comment]
This issue still occurs on async tests.

Run under cursor:
![obraz](https://github.com/Issafalcon/neotest-dotnet/assets/24943089/ba2e55c1-32c3-464b-9183-5e2eb55a2e6e)

Run under cursor:
![obraz](https://github.com/Issafalcon/neotest-dotnet/assets/24943089/faaf7787-0bde-47db-8e38-4983c0451162)

Run all in file:
![obraz](https://github.com/Issafalcon/neotest-dotnet/assets/24943089/15733482-e949-4e46-bb29-dca7760c548e)
