### ISSUE TITLE
Debugged tests do not report correct results

### ISSUE THREAD

**Issue by foldedwave** [Issafalcon/neotest-dotnet#43]
## Summary
When I try to debug a test from the test summary window the test is always marked as a fail.

## Steps to Reproduce
1. Create a new csproj with an xunit test class and passing test method.
2. Open the test summary window
3. Highlight the test method and press 'd' to debug

## Expected Output
Test Passes

## Actual Output
Test is marked as failed with the following message

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/4611157/212561593-11ecb994-2e20-415e-9d75-980ca5dbb61c.png">

## Versions Tested 
Neovim - 0.8.1
neotest - fee5ce9bdc3dff4706a29b012e75025ab376becb
neotest-dotnet - https://github.com/Issafalcon/neotest-dotnet/commit/a90836af097ffc580f61c55e60c1795f73b728f6
dotnet - 6.0.405
linux - ubuntu 20.04 (x64)

If you would like to replicate exactly what I am seeing you can use my test repo - https://github.com/foldedwave/nvim-testing
Ensure you use nvim.sh rather than nvim-dev.sh and run :PackerSync before running the tests.

**Comment by Issafalcon** [comment]
Hi @foldedwave - Yes, this is a limitation with the plugin at the moment due to the way it handles the output of the debugger, rather than the output from neotest when it's parsing the test output.

But thanks for raising this as it is an item on my TODO list!
