### ISSUE TITLE
is there an ability to see output from ITestOutputHelper?????

### ISSUE THREAD

**Issue by ruahman** [Issafalcon/neotest-dotnet#45]
Hello,

I love this this plugin.  Great job.
However I was wondering if it's possible if I could configure neotest.dotnet to display the output passed in to ITestOutputHelper

![image](https://user-images.githubusercontent.com/360398/214747655-d0b34abe-c729-4e38-ade3-c9b2a86ec426.png)

normally I run the following command on the terminal if I want to see the output

![image](https://user-images.githubusercontent.com/360398/214748107-2167d4bc-ea55-41fa-8de5-201efe738363.png)

is there a way to pass  " -l 'console;verbosity=detailed' "   to neotest.dotnet????

**Comment by Issafalcon** [comment]
Hi @ruahman , glad you like it!

It isn't possible at the moment, but it's definitely a good idea to add the option to pass additional arguments. 

I'll add this in when I next get the chance. I'm just setting up unit testing in the project at the moment with a few starter tests, then I can get this feature in.

**Comment by ruahman** [comment]
Okay, great  looking forward to it.

**Comment by Issafalcon** [comment]
Hi @ruahman - Sorry this took so long to add in. It's been tricky to find time to work on the adapter recently. For your case, the --logger option can't be changed because the adapter requires a specific setting for this, but the verbosity can be changed, as indicated in the README updates.
