### ISSUE TITLE
Can't run single/nearest test as no test is found.

### ISSUE THREAD

**Issue by JesperLundberg** [Issafalcon/neotest-dotnet#50]
I can't get the single/nearest test to run properly.
The one that uses `require("neotest").run.run()`.

Run entire file works fine (`require("neotest").run.run(vim.fn.expand("%"))`).

I've checked and rechecked the instructions both here and in the neotest repo and I've configured everything as instructed.
Besides, when testing the entire file it works fine. This leads me to believe that the issue is not setup of the test runner (unless possibly something specific regarding running just one test, can't see how that would work though).

I'm running the lastest version of neovim (0.9) and the latest versions of the neotest and neotest-dotnet plugins.

I've also checked with rider and the tests work fine there (i.e. nothing wrong with the code).

I do get a message and it looks like this:
[image posted on reddit](https://preview.redd.it/fiatm0rw1ata1.png?width=1146&format=png&auto=webp&v=enabled&s=70fe71197c201e6414bba9720d4bec4d5726a7fb)

Not sure if it's of any use but I'll post the thread on reddit here as well [reddit thread](https://www.reddit.com/r/neovim/comments/12hjr7s/neotest_dotnet_works_for_full_file_but_cant_find/)

Any other ideas on what this could be?

**Comment by Issafalcon** [comment]
Hi @JesperLundberg - Thanks for raising the issue.

I've not had chance to get back to working on this plugin in the last couple months, but there are a few outstanding issues with it that I'm aware of.  I have a feeling that the issue you're seeing has been raised before.

Can you clarify a couple of things for me please:
1. What test runner are you using?
2. Is it a single test or is it parameterized? Which of the test framework attributes are you using on the test itself?

Cheers

**Comment by JesLun** [comment]
Of course. I knew that there was something I missed.

1. I'm using nUnit.
2. It's a single non-parametized test with the attribute [Test] (per nUnit standard).

I did read through all the open and closed issues here on github but I might have missed it?

**Comment by Issafalcon** [comment]
Grand, thanks for that!

Ah, OK. Yes I see now.

I initially thought it might have been related to https://github.com/Issafalcon/neotest-dotnet/issues/27, but looks like it is a separate issue.

Hopefully I can get back working on this soon and really nail down some of the outstanding issues like this one.

**Comment by JesLun** [comment]
Yeah, it's not the same. Might be related somehow though.

I'm not knowledgeble about lua enough to look into this deeper myself.

I'm just starting my journey into neovim and also lua.

If you need any more info from me just shout!

**Comment by Issafalcon** [comment]
Hi @JesLun - I've recently added a number of changes that fix a few related issues. Hopefully it's caught yours in that fix-batch as well.

Let me know if it's been resolved. Worth noting you'll need to update neotest core to the latest version as well.

**Comment by JesperLundberg** [comment]
Yes, this issue is resolved now!

I can run a single test and I can also debug a test.
Debugging tests still reports failed and returns the output from dotnet test but that is another issue and since it's still open I guess that isn't a part of these fixes.

Big thanks for the quick fix!

**Comment by Issafalcon** [comment]
Glad to hear!

You caught me at a good time. It's been a while since I've been able to work on this adapter. If you raised this a month ago, the fix might not have been so quick 😄

**Comment by lispercat** [comment]
Looks like I have that issue with the latest plugin.

**Comment by Issafalcon** [comment]
Hi @lispercat . I'm just getting round to addressing issues raised against my plugins. Life changes have meant I've had to move these side projects of mine to lower priority, but just posting to say it's still on my radar to fix, and I'll get back to it as soon as I can.
