### ISSUE TITLE
NUnit TestCaseSource Attribute

### ISSUE THREAD

**Issue by SuborbitalSentinel** [Issafalcon/neotest-dotnet#61]
Is there any interest in supporting NUnit's TestCaseSource attribute?
https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html

**Comment by Issafalcon** [comment]
Hi @SuborbitalSentinel. Yeah, for sure. There are a bunch of attributes that need adding to the adapter, so I'll be working my way through them, as time allows.
