### ISSUE TITLE
Feature Request new vs-code LSP

### ISSUE THREAD

**Issue by timotESC** [Issafalcon/neotest-dotnet#77]
Hello,

First of all thank you for this amazing project and the constant updates. I appreciated this project since the beginning.
I am not sure if you heard of the new Language-Server(LS) from Microsoft which they include in their new C#-Dev-Kit in VS-Code.

The LS should be and stay open-source and they worked also together with the maintainers of omnisharp. I think the future is leaning towards this new LS and it is also amazing how much faster it is already. 
There is still some work to be done, especially in the integration into neovim. But I thought it could be good if this project will also be able to support this new LS. 
I guess basically it shouldn't matter what LS is behind for this project, but I tried one time to run some tests and it didn't find any...

So maybe it is just a small adaptation or maybe it's more work. But I wanted to ask if it would be possible to check it out, such that if the LS is more mature in neovim it will already be compatible with this project.

To follow the development it is easiest to follow [this issue](https://github.com/neovim/nvim-lspconfig/issues/2657) and there is also [described](https://github.com/neovim/nvim-lspconfig/issues/2657#issuecomment-1766182029) how to get the new LS running. Besides a few tweaks it went quite painless for me.

Thank you

**Comment by Issafalcon** [comment]
Hi @timotESC . Thanks for the appreciation!

Whilst it would be great if we could use a language server in this adapter, the core neotest plugin works mainly through treesitter and it's API, and as such, so do the adapters.

I don't leverage any LSP's in the adapter (although I did to begin with when starting this adapter, but it was just not worth it, and only gave limited information that was relevant to locating tests), so a new language server really wouldn't be something that would have any bearing on this project. 

However, thanks for making a suggestion and pointing me towards something shiny to investigate!
