### ISSUE TITLE
Test cases with custom attributes are not discovered

### ISSUE THREAD

**Issue by cizra** [Issafalcon/neotest-dotnet#78]
If a test case is labeled with attributes other than standard xUnit/whatever `[Fact]`, they're not discovered.

```csharp
using Xunit;
using Exercism.Tests;

public class LuciansLusciousLasagnaTests
{
    [Fact]
    [Task(1)] // remove this line to make neotest-dotnet work
    public void Expected_minutes_in_oven() => Assert.Equal(40, new Lasagna().ExpectedMinutesInOven());
}
```

Repro:
- clone or download https://github.com/exercism/csharp/tree/main/exercises/concept/lucians-luscious-lasagna
- try running tests, they're not discovered
- remove the `[Task(n)]` attribute from test cases, rerun tests
- observe that tests are now discovered and executed successfully.

**Comment by Issafalcon** [comment]
Hi @cizra - please see the [README](https://github.com/Issafalcon/neotest-dotnet#usage)

I have reproduced the issue you mention before adding in my custom attributes to the config, and then after adding in the following, the test is discoverable and passes:

```
        require("neotest-dotnet")({
          discovery_root = "solution",
          custom_attributes = {
            xunit = { "Task" },
          },
        }),
```

I'll close this issue as there is already a fix for custom attributes.

**Comment by cizra** [comment]
Thanks!
