### ISSUE TITLE
Test appears as failed when using `Fact(DisplayName = "test name")`

### ISSUE THREAD

**Issue by bartoszluka** [Issafalcon/neotest-dotnet#79]
![true negative](https://github.com/Issafalcon/neotest-dotnet/assets/72729880/51b776da-72f8-4297-a824-8a8a4c893e5a)

When using `DisplayName` property on `Fact` attribute, the test appears as failed even though it actually succeeded.
Not setting this property works fine.

this is a true negative or a false positive (not sure which one)

version info:

neotest

```
url    https://github.com/nvim-neotest/neotest
branch master
commit d424d26
```

neotest-dotent

```
url     https://github.com/Issafalcon/neotest-dotnet
version 1.5.1
tag     stable
branch  main
commit  f7bdb60
```

neovim:
```
NVIM v0.10.0-dev-582d7f4
Build type: RelWithDebInfo
LuaJIT 2.1.1699801871
```

**Comment by Issafalcon** [comment]
Thanks for raising the issue @bartoszluka . I'll take a look at it soon.

**Comment by bartoszluka** [comment]
I can confirm that it works now. Thank you!
