### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by Anakael** [Issafalcon/neotest-dotnet#93]
I have around 800 tests in my working project.
After I call :TestSummary in one test class, my CPU fully consumed by many .NET HOSTs and all system is freezing.

**Comment by B3RR10** [comment]
I'm having the same problem. Not only the CPU but also the RAM is consumed completely.

I'm using xUnit, and for me, it happens when I execute the nearest test, without opening the test summary.

**Comment by Issafalcon** [comment]
@Anakael / @B3RR10 - Could you add some more detail? Specifically:

1. Your neotest configuration
2. The version of the neotest core plugin you are using
3. Any `neotest.log` output that shows how frequently the `dotnet test` command is running. 
  - Clear out the logs
  - Start the action that causes the issue
  - Check the logs and search for `DotNetUtils.get_test_full_names output`
  
 I suspect that the dotnet test command is being triggered too often for some reason. Last time I load tested the plugin was a while ago, with an older version of `neotest` core, and admittedly with around 350 xunit tests.

I need to get some more info and build in some sort of caching of the command, it sounds like. Until then you can pin `neotest-dotnet` to commit `4ebc336c19646791b75c2ae1a30f2b8e403b9d63` to revert back to when the plugin used a different mechanism.

**Comment by B3RR10** [comment]
Nice! I'll test it tomorrow. Thanks a lot!

**Comment by Anakael** [comment]
Now summary works fine.
But before tests are discovered running test from code doesn't work:
![image](https://github.com/Issafalcon/neotest-dotnet/assets/17771546/98072abf-ab6b-4062-8149-335c942b12fa)
